apiVersion: v1
kind: Service
metadata:
  name: apphub-flink-jobmanager
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
    app.kubernetes.io/part-of: apphub-streaming
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
    app.kubernetes.io/part-of: apphub-streaming
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: web
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: apphub-flink-jobmanager-headless
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
    app.kubernetes.io/part-of: apphub-streaming
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: jobmanager
    app.kubernetes.io/part-of: apphub-streaming
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
