apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apphub-redpanda
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: apphub-streaming
spec:
  serviceName: apphub-redpanda-headless
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
      app.kubernetes.io/part-of: apphub-streaming
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/part-of: apphub-streaming
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:1.37
          command:
            - sh
            - -c
            - |
              chown -R 101:101 /var/lib/redpanda/data
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v24.2.3
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -eu
              ordinal=${POD_NAME##*-}
              fqdn="${POD_NAME}.apphub-redpanda-headless.${POD_NAMESPACE}.svc.cluster.local"
              rpk redpanda start \
                --check=false \
                --node-id ${ordinal} \
                --overprovisioned \
                --smp 1 \
                --memory 2G \
                --reserve-memory 0M \
                --kafka-addr PLAINTEXT://0.0.0.0:9092 \
                --advertise-kafka-addr PLAINTEXT://$fqdn:9092 \
                --rpc-addr 0.0.0.0:33145 \
                --advertise-rpc-addr $fqdn:33145 \
                --pandaproxy-addr 0.0.0.0:8082 \
                --advertise-pandaproxy-addr $fqdn:8082
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
            - containerPort: 8082
              name: pandaproxy
            - containerPort: 33145
              name: rpc
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 4Gi
          readinessProbe:
            httpGet:
              path: /v1/cluster/health_overview
              port: admin
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/brokers
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: redpanda
          app.kubernetes.io/part-of: apphub-streaming
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
