apiVersion: v1
kind: Service
metadata:
  name: apphub-filestore
  labels:
    app.kubernetes.io/name: filestore
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: apphub-runtime
spec:
  selector:
    app.kubernetes.io/name: filestore
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: apphub-runtime
  ports:
    - name: http
      port: 4300
      targetPort: 4300
  type: ClusterIP
