apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphub-flink-jobmanager
spec:
  template:
    spec:
      containers:
        - name: jobmanager
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: clickhouse-s3
                  key: CLICKHOUSE_S3_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: clickhouse-s3
                  key: CLICKHOUSE_S3_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: auto
            - name: AWS_DEFAULT_REGION
              value: auto
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: apphub-flink-jobmanager
            - name: MINIO_ROOT_USER
              $patch: delete
            - name: MINIO_ROOT_PASSWORD
              $patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphub-flink-taskmanager
spec:
  template:
    spec:
      containers:
        - name: taskmanager
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: clickhouse-s3
                  key: CLICKHOUSE_S3_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: clickhouse-s3
                  key: CLICKHOUSE_S3_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: auto
            - name: AWS_DEFAULT_REGION
              value: auto
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: apphub-flink-jobmanager
            - name: MINIO_ROOT_USER
              $patch: delete
            - name: MINIO_ROOT_PASSWORD
              $patch: delete
