apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apphub-minio-data
  labels:
    app.kubernetes.io/name: minio-data
    app.kubernetes.io/part-of: apphub-infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
