apiVersion: v1
kind: Service
metadata:
  name: apphub-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: apphub-infra
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: apphub-infra
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
