apiVersion: v1
kind: Service
metadata:
  name: apphub-clickhouse-internal
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: apphub-runtime
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
