apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apphub-system

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - rbac.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/bootstrap-job.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/pvc.yaml
  - minio/bootstrap-job.yaml
  - catalog/service.yaml
  - catalog/deployments.yaml
  - metastore/service.yaml
  - metastore/deployment.yaml
  - filestore/service.yaml
  - filestore/deployments.yaml
  - timestore/service.yaml
  - timestore/deployments.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress.yaml
