apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphub-frontend
  labels:
    app.kubernetes.io/name: apphub-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: apphub-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apphub-frontend
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: apphub-runtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apphub-frontend
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: apphub-runtime
    spec:
      containers:
        - name: nginx
          image: apphub/frontend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
