apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphub-metastore-api
  labels:
    app.kubernetes.io/name: metastore
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: apphub-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metastore
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: apphub-runtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metastore
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: apphub-runtime
    spec:
      containers:
        - name: api
          image: apphub/metastore:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: apphub-core-config
            - secretRef:
                name: apphub-core-secrets
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "4100"
          ports:
            - containerPort: 4100
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
